spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.vsndedkgqefqckcinvsd
    password: 98tq7qmc0DoeM0k9
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jmx:
    enabled: true
  application:
    admin:
      enabled: true

management:
  endpoints:
    jmx:
      exposure:
        include: "*"

logging:
  level:
    root: debug
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug
auth:
  jwt:
    issuer: team.sprata.com
    secret: P04c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 3600000


