spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
    username: postgres.vsndedkgqefqckcinvsd
    password: jqG20NCKMA3G5XFM
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: info
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug

auth:
  jwt:
    issuer: team.sprata.com
    secret: P04c8z41Hia5gJG3oeuFJMRYBB4Ws4aZ
    accessTokenExpirationHour: 3600000